//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace NuClear.ValidationRules.Import.Model.CommonFormat.flowNomenclatures.NomenclatureElement {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NomenclatureElement : NomenclatureElementSimple {
        
        private NomenclatureElementSimple[] compositionField;
        
        private bool isCompositionOptionalField;
        
        private bool isDeletedField;
        
        public NomenclatureElement() {
            this.isCompositionOptionalField = false;
            this.isDeletedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ChildPosition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NomenclatureElementSimple[] Composition {
            get {
                return this.compositionField;
            }
            set {
                this.compositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsCompositionOptional {
            get {
                return this.isCompositionOptionalField;
            }
            set {
                this.isCompositionOptionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NomenclatureElement))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NomenclatureElementSimple {
        
        private Platform[] platformsField;
        
        private Country[] countriesField;
        
        private ProdavanMetadata prodavanMetadataField;
        
        private long codeField;
        
        private string defaultNameField;
        
        private int productCodeField;
        
        private int productCategoryCodeField;
        
        private long nomenclatureCategoryCodeField;
        
        private LinkObjectType linkObjectTypeField;
        
        private int linkObjectsMaxCountField;
        
        private bool linkObjectsMaxCountFieldSpecified;
        
        private AdvModel advModelField;
        
        private int advTypeCodeField;
        
        private bool isControlledByAmountField;
        
        private bool isAllowedInAgileOrdersField;
        
        private bool isAllowedToEditAdvMaterialsInBizAccountField;
        
        private int orderNoField;
        
        private bool orderNoFieldSpecified;
        
        private PositionsGroup positionsGroupField;
        
        private int methodForDeterminingTheCountOfSalesField;
        
        private ContentSales contentSalesField;
        
        private string gradeCodeField;
        
        private bool isAllowedProdavanSalesField;
        
        private string descriptionField;
        
        private long previewImageCodeField;
        
        private bool previewImageCodeFieldSpecified;
        
        public NomenclatureElementSimple() {
            this.isControlledByAmountField = false;
            this.isAllowedInAgileOrdersField = false;
            this.isAllowedToEditAdvMaterialsInBizAccountField = false;
            this.isAllowedProdavanSalesField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Platform[] Platforms {
            get {
                return this.platformsField;
            }
            set {
                this.platformsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Country[] Countries {
            get {
                return this.countriesField;
            }
            set {
                this.countriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProdavanMetadata ProdavanMetadata {
            get {
                return this.prodavanMetadataField;
            }
            set {
                this.prodavanMetadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultName {
            get {
                return this.defaultNameField;
            }
            set {
                this.defaultNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ProductCategoryCode {
            get {
                return this.productCategoryCodeField;
            }
            set {
                this.productCategoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long NomenclatureCategoryCode {
            get {
                return this.nomenclatureCategoryCodeField;
            }
            set {
                this.nomenclatureCategoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LinkObjectType LinkObjectType {
            get {
                return this.linkObjectTypeField;
            }
            set {
                this.linkObjectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LinkObjectsMaxCount {
            get {
                return this.linkObjectsMaxCountField;
            }
            set {
                this.linkObjectsMaxCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LinkObjectsMaxCountSpecified {
            get {
                return this.linkObjectsMaxCountFieldSpecified;
            }
            set {
                this.linkObjectsMaxCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AdvModel AdvModel {
            get {
                return this.advModelField;
            }
            set {
                this.advModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AdvTypeCode {
            get {
                return this.advTypeCodeField;
            }
            set {
                this.advTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsControlledByAmount {
            get {
                return this.isControlledByAmountField;
            }
            set {
                this.isControlledByAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsAllowedInAgileOrders {
            get {
                return this.isAllowedInAgileOrdersField;
            }
            set {
                this.isAllowedInAgileOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsAllowedToEditAdvMaterialsInBizAccount {
            get {
                return this.isAllowedToEditAdvMaterialsInBizAccountField;
            }
            set {
                this.isAllowedToEditAdvMaterialsInBizAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderNoSpecified {
            get {
                return this.orderNoFieldSpecified;
            }
            set {
                this.orderNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PositionsGroup PositionsGroup {
            get {
                return this.positionsGroupField;
            }
            set {
                this.positionsGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int MethodForDeterminingTheCountOfSales {
            get {
                return this.methodForDeterminingTheCountOfSalesField;
            }
            set {
                this.methodForDeterminingTheCountOfSalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ContentSales ContentSales {
            get {
                return this.contentSalesField;
            }
            set {
                this.contentSalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GradeCode {
            get {
                return this.gradeCodeField;
            }
            set {
                this.gradeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsAllowedProdavanSales {
            get {
                return this.isAllowedProdavanSalesField;
            }
            set {
                this.isAllowedProdavanSalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long PreviewImageCode {
            get {
                return this.previewImageCodeField;
            }
            set {
                this.previewImageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreviewImageCodeSpecified {
            get {
                return this.previewImageCodeFieldSpecified;
            }
            set {
                this.previewImageCodeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Platform {
        
        private int platformCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int PlatformCode {
            get {
                return this.platformCodeField;
            }
            set {
                this.platformCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProdavanMetadata {
        
        private string advTypeField;
        
        private string categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AdvType {
            get {
                return this.advTypeField;
            }
            set {
                this.advTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Localization {
        
        private string langField;
        
        private string nameField;
        
        private string publicNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PublicName {
            get {
                return this.publicNameField;
            }
            set {
                this.publicNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Country {
        
        private Localization[] localizationsField;
        
        private long countryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Localization[] Localizations {
            get {
                return this.localizationsField;
            }
            set {
                this.localizationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum LinkObjectType {
        
        /// <remarks/>
        Firm,
        
        /// <remarks/>
        CategorySingle,
        
        /// <remarks/>
        CategoryMultiple,
        
        /// <remarks/>
        CategoryMultipleAsterix,
        
        /// <remarks/>
        AddressSingle,
        
        /// <remarks/>
        AddressMultiple,
        
        /// <remarks/>
        AddressCategorySingle,
        
        /// <remarks/>
        AddressCategoryMultiple,
        
        /// <remarks/>
        AddressFirstLevelCategorySingle,
        
        /// <remarks/>
        AddressFirstLevelCategoryMultiple,
        
        /// <remarks/>
        ThemeMultiple,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum AdvModel {
        
        /// <remarks/>
        CPS,
        
        /// <remarks/>
        FH,
        
        /// <remarks/>
        MFH,
        
        /// <remarks/>
        CPU,
        
        /// <remarks/>
        CPM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum PositionsGroup {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        MediaAdvertising,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ContentSales {
        
        /// <remarks/>
        WithoutContent,
        
        /// <remarks/>
        ContentIsRequired,
        
        /// <remarks/>
        ContentIsNotRequired,
    }
}
