//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.8.3928.0.
//
namespace NuClear.ValidationRules.Import.Model.CommonFormat.flowFinancialData.DebitsInfo {
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DebitsInfo {

        private Debit[] clientDebitsField;

        private string organizationUnitCodeField;

        private AccountingMethod accountingMethodField;

        private System.DateTime startDateField;

        private System.DateTime endDateField;

        private float clientDebitTotalAmountField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Debit[] ClientDebits {
            get {
                return this.clientDebitsField;
            }
            set {
                this.clientDebitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OrganizationUnitCode {
            get {
                return this.organizationUnitCodeField;
            }
            set {
                this.organizationUnitCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AccountingMethod AccountingMethod {
            get {
                return this.accountingMethodField;
            }
            set {
                this.accountingMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float ClientDebitTotalAmount {
            get {
                return this.clientDebitTotalAmountField;
            }
            set {
                this.clientDebitTotalAmountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Debit {

        private DebitNonStandardCategoryDistribution[] nonStandardCategoryDistributionField;

        private long accountCodeField;

        private string subaccountCodeField;

        private string organizationUnitDestCodeField;

        private long legalEntityBranchCodeField;

        private long profileCodeField;

        private bool profileCodeFieldSpecified;

        private int orderTypeField;

        private string orderNumberField;

        private System.DateTime signupDateField;

        private float amountField;

        private string mediaInfoField;

        private System.DateTime factBeginDateField;

        private System.DateTime factEndDateField;

        private string clientOrderNumberField;

        private bool isRegionalField;

        private string curatorField;

        public Debit() {
            this.isRegionalField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NonStandardCategoryDistribution")]
        public DebitNonStandardCategoryDistribution[] NonStandardCategoryDistribution {
            get {
                return this.nonStandardCategoryDistributionField;
            }
            set {
                this.nonStandardCategoryDistributionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long AccountCode {
            get {
                return this.accountCodeField;
            }
            set {
                this.accountCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SubaccountCode {
            get {
                return this.subaccountCodeField;
            }
            set {
                this.subaccountCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OrganizationUnitDestCode {
            get {
                return this.organizationUnitDestCodeField;
            }
            set {
                this.organizationUnitDestCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long LegalEntityBranchCode {
            get {
                return this.legalEntityBranchCodeField;
            }
            set {
                this.legalEntityBranchCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ProfileCode {
            get {
                return this.profileCodeField;
            }
            set {
                this.profileCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProfileCodeSpecified {
            get {
                return this.profileCodeFieldSpecified;
            }
            set {
                this.profileCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime SignupDate {
            get {
                return this.signupDateField;
            }
            set {
                this.signupDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MediaInfo {
            get {
                return this.mediaInfoField;
            }
            set {
                this.mediaInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime FactBeginDate {
            get {
                return this.factBeginDateField;
            }
            set {
                this.factBeginDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime FactEndDate {
            get {
                return this.factEndDateField;
            }
            set {
                this.factEndDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClientOrderNumber {
            get {
                return this.clientOrderNumberField;
            }
            set {
                this.clientOrderNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsRegional {
            get {
                return this.isRegionalField;
            }
            set {
                this.isRegionalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Curator {
            get {
                return this.curatorField;
            }
            set {
                this.curatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DebitNonStandardCategoryDistribution {

        private long categoryCodeField;

        private int countField;

        private bool countFieldSpecified;

        private float amountField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long CategoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum AccountingMethod {

        /// <remarks/>
        Fact,

        /// <remarks/>
        Planned,

        /// <remarks/>
        NonStandard,

        /// <remarks/>
        RocketData,
    }
}
